name: CI Python
on:
  push:
    paths:
      - 'src/server/**'
      - '.github/workflows/ci-python.yml'
  pull_request:
    paths:
      - 'src/server/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi
        working-directory: src/server
      - name: Run tests
        run: pytest -q
        working-directory: src/server
