name: CI Web
on:
  push:
    paths:
      - 'src/webviewer/**'
      - '.github/workflows/ci-web.yml'
  pull_request:
    paths:
      - 'src/webviewer/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm i
        working-directory: src/webviewer
      - name: Build
        run: pnpm build
        working-directory: src/webviewer
